server:
  port: 9090
spring:
  application:
    name: gateway
  redis:
    host: 123.207.210.137
    port: 6379
    lettuce:
      pool:
        max-active: -1
        max-idle: 500
        min-idle: 50
        max-wait: -1
      timeout: 30000
    password: Yqzx1925@qq.com
  cloud:
    nacos:
      server-addr: 123.207.210.137:8848 #nacos地址
    gateway:
      routes:
        - id: user-service #路由标识，唯一
          uri: lb://userservice #路由目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/** #路径断言，判断路径是否是以/user开头，如果是则符合
        - id: car-service
          uri: lb://carservice
          predicates:
            - Path=/car/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/orders/**
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: 10 #令牌桶填充速率，每秒10个
            redis-rate-limiter.burstCapacity: 20 #令牌桶容量，20
            key-resolver: "#{@apiKeyResolver}"
