server:
  port: 8082
spring:
  application:
    name: orderservice
  cloud:
    nacos:
      server-addr: 123.207.210.137:8848 #nacos地址

    # 流控，熔断降级，sentinel控制台地址
    sentinel:
      transport:
        dashboard: 123.207.210.137:8180
        port: 8180
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://123.207.210.137:3306/order?useSSL=false&characterEncoding=utf-8
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 123.207.210.137
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: 1234

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
#debug: true

orderservice:
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则

## 分布式事务
#seata:
#  registry:
#    type: nacos
#    nacos:
#      server-addr: 124.222.212.173:8848
#      namespace: ""
#      group: DEFAULT_GROUP
#      application: seata-server #tc服务名称
#      username: nacos
#      password: nacos
#  data-source-proxy-mode: AT
#  tx-service-group: orderservice-group #事务组
#  service:
#    vgroup-mapping: #事务组与tc服务集群的映射关系
#      orderservice-group: default

feign:
  httpclient:
    max-connections: 200
    max-connections-per-route: 50
  client:
    config:
      default:
        logger-level: BASIC
        connect-timeout: 300000
        read-timeout: 300000