server:
  port: 9090
spring:
  application:
    name: gateway
  cloud:
    nacos:
      server-addr: 124.222.212.173:8848 #nacos地址
    gateway:
      routes:
        - id: user-service #路由标识，唯一
          uri: lb://userservice #路由目标地址
          predicates: #路由断言，判断请求是否符合规则
            - Path=/user/** #路径断言，判断路径是否是以/user开头，如果是则符合
        - id: car-service
          uri: lb://carservice
          predicates:
            - Path=/car/**
        - id: order-service
          uri: lb://orderservice
          predicates:
            - Path=/orders/**