server:
  port: 8084
spring:
  application:
    name: emailservice
  cloud:
    nacos:
      server-addr: 124.222.212.173:8848 #nacos
  rabbitmq:
    port: 5672
    virtual-host: /
    host: 124.222.212.173
    username: root
    password: root
    #消费者确认机制
    listener:
      simple:
        prefetch: 1 #每次取一条消息消费
        acknowledge-mode: auto #消费者消息确认机制
        retry:
          enabled: true #开启消费者重试
          initial-interval: 1000 #初始间隔时间
          multiplier: 3 #重试设置倍数
          max-attempts: 5 #最大重试次数
  redis:
    host: 124.222.212.173
    port: 6379
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
    password: 1234